env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:  {
  'indent': 'off',
  no-console: 0,
  import/extensions: 0,
  allowIndentationTabs: true,
}
