env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:  {
  indent: 0,
  no-console: 0,
  import/extensions: 0,
  no-tabs: ["error", { allowIndentationTabs: true }],
}
